### PR TITLE
fix run mode config ineffective issue in a2a remote agent

### LINKED ISSUE #486: Non-streaming mode ineffective in a2a remote agent
**Describe the bug**
When connecting to a remote remoteAgent via A2A, non-streaming requests will receive two messages in response. 

Image

Image

However, streaming requests work as expected and only receive one normal message.

Image

**To Reproduce**

func main() {
	ctx := context.Background()

	remoteAgent, err := remoteagent.NewA2A(remoteagent.A2AConfig{
		Name:            "remoteAgent",
		AgentCardSource: "http://localhost:8001/a2a/invoke",
	})
	if err != nil {
		log.Fatalf("Failed to create a remote agent: %v", err)
	}

	config := &launcher.Config{
		AgentLoader: agent.NewSingleLoader(remoteAgent),
	}

	l := full.NewLauncher()
	if err = l.Execute(ctx, config, os.Args[1:]); err != nil {
		log.Fatalf("Run failed: %v\n\n%s", err, l.CommandLineSyntax())
	}
}

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS
 - Go version: 1.24.1
 - ADK version: 0.3.0

**Model Information:**
 - gemini-2.5-flash

### PR DESCRIPTION
**Pull request by sjy3**
Resolved the problem that the Run method of the remote agent does not verify the StreamingMode parameter in the external run configuration, which resulted in non-streaming requests failing to take effect.

Fixes #486

### CODE REVIEW

**Comment by sjy3** [comment]
@yarolegovich

File: agent/remoteagent/a2a_agent.go [hunk 1]
```diff
@@ -204,6 +204,16 @@ func (a *a2aAgent) run(ctx agent.InvocationContext, cfg A2AConfig) iter.Seq2[*se
 				}
 			}
 		}
+
+		if ctx.RunConfig().StreamingMode == agent.StreamingModeNone {
```
Comment (yarolegovich) [inline agent/remoteagent/a2a_agent.go:207]: the fix looks good, thanks!

can you please extend test case struct to have `noStreaming: bool` in either TestRemoteAgent_ADK2ADK or TestRemoteAgent_ADK2A2A (a2a_agent_test.go).

then copy one of the existing testcases and modify wantResponses to see that it only emits a single event which is an aggregation of all the events emitted on remote if invoked in non-streaming mode.

Comment (sjy3) [reply agent/remoteagent/a2a_agent.go]: Done

File: agent/remoteagent/a2a_agent_test.go [hunk 2]
```diff
@@ -89,6 +89,34 @@ func newInvocationContext(t *testing.T, events []*session.Event) agent.Invocatio
 	return ic
 }
 
+func newInvocationContextWithStreamingMode(t *testing.T, events []*session.Event, noStreaming bool) agent.InvocationContext {
```
Comment (yarolegovich) [inline agent/remoteagent/a2a_agent_test.go]: I'd rather reduce context setup code duplication:

<details>

```diff
diff --git a/agent/remoteagent/a2a_agent_test.go b/agent/remoteagent/a2a_agent_test.go
index 9dbda44..96a2263 100644
--- a/agent/remoteagent/a2a_agent_test.go
+++ b/agent/remoteagent/a2a_agent_test.go
@@ -73,23 +73,10 @@ func newA2ARemoteAgent(t *testing.T, name string, server *httptest.Server) agent
 }

 func newInvocationContext(t *testing.T, events []*session.Event) agent.InvocationContext {
-	t.Helper()
-	ctx := t.Context()
-	service := session.InMemoryService()
-	resp, err := service.Create(ctx, &session.CreateRequest{AppName: t.Name(), UserID: "test"})
-	if err != nil {
-		t.Fatalf("sessionService.Create() error = %v", err)
-	}
-	for _, event := range events {
-		if err := service.AppendEvent(ctx, resp.Session, event); err != nil {
-			t.Fatalf("sessionService.AppendEvent() error = %v", err)
-		}
-	}
-	ic := icontext.NewInvocationContext(ctx, icontext.InvocationContextParams{Session: resp.Session})
-	return ic
+	return newInvocationContextWithStreamingMode(t, events, agent.StreamingModeSSE)
 }

-func newInvocationContextWithStreamingMode(t *testing.T, events []*session.Event, noStreaming bool) agent.InvocationContext {
+func newInvocationContextWithStreamingMode(t *testing.T, events []*session.Event, streamingMode agent.StreamingMode) agent.InvocationContext {
 	t.Helper()
 	ctx := t.Context()
 	service := session.InMemoryService()
@@ -103,11 +90,6 @@ func newInvocationContextWithStreamingMode(t *testing.T, events []*session.Event
 		}
 	}

-	streamingMode := agent.StreamingModeSSE
-	if noStreaming {
-		streamingMode = agent.StreamingModeNone
-	}
-
 	ic := icontext.NewInvocationContext(ctx, icontext.InvocationContextParams{
 		Session: resp.Session,
 		RunConfig: &agent.RunConfig{
@@ -383,7 +365,11 @@ func TestRemoteAgent_ADK2ADK(t *testing.T) {
 			executor := newADKEventReplay(t, tc.remoteEvents)
 			remoteAgent := newA2ARemoteAgent(t, "a2a", startA2AServer(executor))

-			ictx := newInvocationContextWithStreamingMode(t, []*session.Event{newUserHello()}, tc.noStreaming)
+			mode := agent.StreamingModeSSE
+			if tc.noStreaming {
+				mode = agent.StreamingModeNone
+			}
+			ictx := newInvocationContextWithStreamingMode(t, []*session.Event{newUserHello()}, mode)
 			gotEvents, err := runAndCollect(ictx, remoteAgent)
 			if err != nil {
 				t.Fatalf("agent.Run() error = %v", err)
```
</details>

File: agent/remoteagent/a2a_agent.go (hunk 1 above)
Comment (yarolegovich) [reply agent/remoteagent/a2a_agent.go:207]: thanks, now we need to make it pass 🙂 
I can have a look this week or will gladly review if you try addressing it

Comment (sjy3) [reply agent/remoteagent/a2a_agent.go:207]: Got it! I've finished the fixes. Feel free to take a look whenever you have time this week — appreciate your review in advance!

**Review by dpasiukevich — DISMISSED** [review]

**Comment by sjy3** [comment]
@dpasiukevich files properly formatted
