### PR TITLE
fix: resolve nil pointer in tool.Context.SearchMemory in webui mode

### LINKED ISSUE #477: nil pointer panic on SearchMemory in tool when starting in webui mode (normal in runner mode)
**Describe the bug**
When starting in the webui mode, a null pointer exception occurs when using SearchMemory in the tool, but it works normally when the runner starts.

panic in tool "search_past_conversations": runtime error: invalid memory address or nil pointer dereference stack: goroutine 50 [running]: runtime/debug.Stack() /Users/go/go1.24.4/src/runtime/debug/stack.go:26 +0x64 google.golang.org/adk/tool/functiontool.(*functionTool[...]).Run.func1() /Users/go/pkg/mod/google.golang.org/adk@v0.3.1-0.20251223085414-415e39855752/tool/functiontool/function.go:153 +0x6c panic({0x1031d32a0?, 0x1039c6570?}) /Users/go/go1.24.4/src/runtime/panic.go:792 +0x124 google.golang.org/adk/internal/toolinternal.(*toolContext).SearchMemory(0x16?, {0x1033494a0, 0x103a28700}, {0x140002e03e0, 0x6}) /Users/go/pkg/mod/google.golang.org/adk@v0.3.1-0.20251223085414-415e39855752/internal/toolinternal/context.go:100 +0x38 main.memorySearchToolFunc({0x1033553c0?, 0x14000122800?}, {{0x140002e03e0?, 0x103349618?}}) /Users/GoProject/veadk-go/examples/memory/long_memory/agent_with_long_memory.go:54 +0x4c google.golang.org/adk/tool/functiontool.(*functionTool[...]).Run(0x103352300, {0x1033553c0, 0x14000122800}, {0x1031fb4e0, 0x140001195c0?})

**To Reproduce**

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"google.golang.org/adk/agent"
	"google.golang.org/adk/agent/llmagent"
	"google.golang.org/adk/cmd/launcher"
	"google.golang.org/adk/cmd/launcher/full"
	"google.golang.org/adk/memory"
	"google.golang.org/adk/model"
	"google.golang.org/adk/model/gemini"
	"google.golang.org/adk/session"
	"google.golang.org/adk/tool"
	"google.golang.org/adk/tool/functiontool"
	"google.golang.org/genai"
)

func LoadLongMemoryTool() (tool.Tool, error) {
	return functiontool.New(
		functiontool.Config{
			Name:        "search_past_conversations",
			Description: "Searches past conversations for relevant information.",
		},
		memorySearchToolFunc,
	)
}

type Args struct {
	Query string `json:"query" jsonschema:"The query to search for in the memory."`
}

type Result struct {
	Results []string `json:"results"`
}

func memorySearchToolFunc(tctx tool.Context, args Args) (Result, error) {

	searchResults, err := tctx.SearchMemory(context.Background(), args.Query)
	if err != nil {
		return Result{}, fmt.Errorf("failed memory search")
	}

	var results []string
	for _, res := range searchResults.Memories {
		if res.Content != nil {
			results = append(results, textParts(res.Content)...)
		}
	}
	return Result{Results: results}, nil
}

func textParts(Content *genai.Content) []string {
	var texts []string
	for _, part := range Content.Parts {
		texts = append(texts, part.Text)
	}
	return texts
}

func onAfterModel(ctx agent.CallbackContext, llmResponse *model.LLMResponse, llmResponseError error) (*model.LLMResponse, error) {
	reqStr, _ := json.Marshal(llmResponse)
	log.Printf("%s [Callback] After Model resp: %s", ctx.AgentName(), string(reqStr))
	if llmResponseError != nil {
		log.Printf("%s [Callback] After Model error: %s", ctx.AgentName(), llmResponseError.Error())
	}
	return nil, nil
}

func main() {
	ctx := context.Background()

	sessionServer := session.InMemoryService()
	memoryServer := memory.InMemoryService()
	memorySearchTool, _ := LoadLongMemoryTool()

	onBeforeAgent := func(ctx agent.CallbackContext) (*genai.Content, error) {
		resp, err := sessionServer.Get(ctx, &session.GetRequest{AppName: ctx.AppName(), UserID: ctx.UserID(), SessionID: ctx.SessionID()})
		if err != nil {
			log.Fatalf("Failed to get completed session: %v", err)
		}
		if err := memoryServer.AddSession(ctx, resp.Session); err != nil {
			log.Fatalf("Failed to add session to memory: %v", err)
		}
		log.Println("")

		log.Printf("[Callback] Session %s added to memory.", ctx.SessionID())
		return nil, nil
	}

	modelName := "gemini-2.5-flash-lite"

	model, err := gemini.NewModel(ctx, modelName, &genai.ClientConfig{
		APIKey: os.Getenv("GOOGLE_API_KEY"),
	})

	if err != nil {
		log.Fatalf("NewModel error：%v", err)
		return
	}

	a, err := llmagent.New(llmagent.Config{
		Model:                model,
		Name:                 "personal_assistant",
		Instruction:          "You are a personal assistant with long-term memory capabilities. Before answering the user's questions, you must invoke the tool to retrieve memory information.",
		Tools:                []tool.Tool{memorySearchTool},
		BeforeAgentCallbacks: []agent.BeforeAgentCallback{onBeforeAgent},
		AfterModelCallbacks:  []llmagent.AfterModelCallback{onAfterModel},
	})
	if err != nil {
		fmt.Printf("NewLLMAgent failed: %v", err)
		return
	}

	config := &launcher.Config{
		AgentLoader:    agent.NewSingleLoader(a),
		SessionService: sessionServer,
		MemoryService:  memoryServer,
	}

	l := full.NewLauncher()
	if err = l.Execute(ctx, config, os.Args[1:]); err != nil {
		log.Fatalf("Run failed: %v\n\n%s", err, l.CommandLineSyntax())
	}
}

**Desktop (please complete the following information):**
 - OS: macOS
 - Go version: 1.24.4
 - ADK version: 0.3.0

**Model Information:**
 - gemini-2.5-flash-lite

### PR DESCRIPTION
**Pull request by sjy3**
### Bug Fix
Fix the null pointer dereference exception of `tool.Context.SearchMemory` in webui startup mode.

### Root Cause
The memory instance was not correctly passed/injected into the context object when the service was launched in the webui mode, which caused the context to hold a nil memory reference. When invoking the `SearchMemory` method, a nil pointer panic was triggered due to accessing the uninitialized memory object.

### Fix Content
1. Correct the memory parameter passing logic in the webui startup entry

### Related Issues

Fixes #477

### CODE REVIEW

**Comment by dpasiukevich** [comment]
WDYT to also add a check in the tool context implementation in SearchMemory method? If memory == nil -> return error.

**Comment by sjy3** [comment]
> WDYT to also add a check in the tool context implementation in SearchMemory method? If memory == nil -> return error.

@dpasiukevich good idea, finished

File: internal/toolinternal/context.go [hunk 1]
```diff
@@ -97,5 +98,8 @@ func (c *toolContext) AgentName() string {
 }
 
 func (c *toolContext) SearchMemory(ctx context.Context, query string) (*memory.SearchResponse, error) {
+	if c.invocationContext.Memory() == nil {
+		return nil, fmt.Errorf("memroy service nil error")
```
Comment (dpasiukevich) [inline internal/toolinternal/context.go]:
```suggestion
		return nil, fmt.Errorf("memory service is not set")
```
